name: Node.js CI

on:
  push:
    branches: [ "main", "master", "develop" ] # Adjust branches as needed
  pull_request:
    branches: [ "main", "master", "develop" ] # Adjust branches as needed

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Test on multiple Node.js versions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Cache npm dependencies

    - name: Install dependencies
      run: npm ci # Use ci for cleaner installs in CI

    - name: Run linters
      run: npm run lint 

    - name: Run tests
      run: npm test # Assumes test script in package.json runs Jest

    - name: Build project (optional)
      run: npm run build 
      # if: github.ref == 'refs/heads/main' # Example: only build on main branch pushes 